.\"Copyright (c) 2010, 2011, 2012, 2013 LEVAI Daniel
.\"All rights reserved.
.\"Redistribution and use in source and binary forms, with or without
.\"modification, are permitted provided that the following conditions are met:
.\"	* Redistributions of source code must retain the above copyright
.\"	notice, this list of conditions and the following disclaimer.
.\"	* Redistributions in binary form must reproduce the above copyright
.\"	notice, this list of conditions and the following disclaimer in the
.\"	documentation and/or other materials provided with the distribution.
.\"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
.\"ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\"WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
.\"DISCLAIMED. IN NO EVENT SHALL LEVAI Daniel BE LIABLE FOR ANY
.\"DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\"(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\"LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
.\"ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\"(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
.\"SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.Dd Jan 14, 2013
.Dt LOGIN_SQL 8
.Os
.Sh NAME
.Nm login_sql
.Nd provides SQL authentication
.Sh SYNOPSIS
.Nm login_sql
.Op Fl s Ar service
.Op Fl v Ar name=value
.Ar user
.Op Ar class
.Sh DESCRIPTION
The
.Nm
utility is called by
.Xr login 1 ,
.Xr su 1 ,
and others to authenticate the
.Ar user
against an SQL database. Currently PostgreSQL and MySQL is supported.
.Pp
The
.Ar user
argument is the login name of the user to be authenticated.
.Pp
The
.Ar service
argument specifies which protocol to use with the
invoking program.
.Ss LOGIN.CONF VARIABLES
The
.Nm
utility uses only the following
.Em optional
.Xr login.conf 5
variable:
.Bl -tag -offset ||| -width |
.It Cm x-sql-cfg_file
Specifies the path name for the configuration file. If you omit this variable, then the default configuration file will be used.
.El
.Ss CONFIGURATION FILE
The configuration file ignores any line which doesn't start with a recognized configuration option. Options are in the form of
.Em option=value.
The following is a list of the usable options.
.Pp
.Em PostgreSQL
specific options:
.Bl -tag -offset ||| -width |
.It Cm pgsql_dbconnection
This is a space separated list of keyword=value pairs. Common keywords include: host, port, dbname, user, password, etc...
.Pp
For more information:
.Pp
http://www.postgresql.org/8.4/static/libpq-connect.html
.Pp
Search for PQconnectdb, and refer to the recognized parameters. Pay attention to the difference between the
.Cm host=
and the
.Cm hostaddr=
options, and their meaning if they are omitted.
.It Cm pgsql_table
The table name in the database which contains the username and password columns.
.It Cm pgsql_user_col
The column's name which contains the username.
.It Cm pgsql_pass_col
The column's name which contains the password.
.It Cm pgsql_scheme_col
The column's name which contains the password scheme. This scheme overrides the global
.Cm digest_alg.
.El
.Pp
.Em MySQL
specific options:
.Bl -tag -offset ||| -width |
.It Cm mysql_host
Host name or IP address.
.It Cm mysql_port
Port number for a TCP/IP connection.
.It Cm mysql_db
Database's name which contains the user/pass.
.It Cm mysql_user
Username used for connecting to the database.
.It Cm mysql_pass
Password used for connecting to the database.
.It Cm mysql_table
Table's name which contains the user/pass.
.It Cm mysql_user_col
The column's name which contains the username.
.It Cm mysql_pass_col
The column's name which contains the password.
.It Cm mysql_scheme_col
The column's name which contains the password scheme. This scheme overrides the global
.Cm digest_alg.
.It Cm mysql_key
Path name to the key file.
.It Cm mysql_cert
Path name to the certificate file.
.It Cm mysql_ca
Path name to the certificate authority file.
.It Cm mysql_capath
Path name to the directory that contains trusted SSL CA certificates in pem format.
.It Cm mysql_cipher
List of permissible ciphers to use for SSL encryption.
.El
.Bd -ragged -offset |||
For the MySQL parameters' valid or default values please read the MySQL documentation here:
.Pp
http://dev.mysql.com/doc/refman/5.1/en/mysql-real-connect.html
.Pp
For the MySQL SSL parameters' valid or default values please read the MySQL SSL documentation here:
.Pp
http://dev.mysql.com/doc/refman/5.1/en/mysql-ssl-set.html
.Ed
.Pp
.Em Miscellaneous
options:
.Bl -tag -offset ||| -width |
.It Cm digest_alg
The message digest or encryption algorithm to use with the user supplied password. This will be the default, which can be overridden with a scheme column in the database table (see MySQL or PostgreSQL options above).
.Pp
You can use any digest which is supported by your OpenSSL library. For more information, enter
.Dl openssl dgst -h
on the command line.
.Pp
On top of that, the
.Cm blowfish
and the
.Cm md5crypt
values make use of the
.Xr crypt 3
function and encrypt the user supplied password with salted
.Cm blowfish
or salted
.Cm md5
encryption algorithms, respectively.
.Pp
The special value
.Cm cleartext
means that the password is stored in clear text in the database, so no hashing is necessary for the password entered.
.It Cm sql_backend
The SQL backend to use for retrieving the password. Valid values are
.Cm pgsql
and
.Cm mysql.
.El
.Sh FILES
.Bl -hang -width ||||||||||||||||||||||||||||||||| -compact
.It Pa /etc/login_sql.conf
Default configuration file
.El
.Ss EXAMPLE CONFIGURATION FILE
.Bd -literal
pgsql_dbconnection=dbname=superdb user=jester password=s3cr3t
pgsql_table=login_info
pgsql_user_col=username
pgsql_pass_col=pwd

mysql_host=mysql.slickmachine.net
mysql_port=12345
mysql_db=login
mysql_user=my_user
mysql_pass=v1lm4
mysql_table=authentication
mysql_user_col=user
mysql_pass_col=pass

digest_alg=sha256
.Ed
.Sh AUTHOR
.Nm
was written by
.An Daniel LEVAI
<leva@ecentrum.hu>.
.Pp
Source, information, bugs:
http://login-sql.googlecode.com
.Sh SEE ALSO
.Xr login 1 ,
.Xr su 1 ,
.Xr login.conf 5 ,
.Xr psql 1 ,
.Xr mysql 1 ,
.Xr openssl 1
